In [13]:
%load_ext autoreload
%autoreload 2

In [1]:
import torch.nn as nn
import torch

In [8]:
class dummy(nn.Module):
    def __init__(self):
        super().__init__()
    def start(self,sz):
        self.temp=torch.randn(size=(sz))
        print(f"original form {self.temp.shape}")
        print(f"transposed form {self.temp.T.shape[0]} ")

In [9]:
temp=dummy()
temp.start((9,8))

original form torch.Size([9, 8])
transposed form 8 


In [10]:
import torch
import torch.nn.functional as F
import math
def scaled_dot_product(query,key,value,mask_opt=False):
    """this is going to be used for 3d inputs"""
    k_dim=key.shape[-1]
    attention_logits=torch.matmul(query,key.transpose(-2,-1))
    attention_logits=attention_logits/math.sqrt(k_dim)
    if mask_opt:
        attention_logits=attention_logits.masked_fill(mask==0,-float("inf"))
    #attention=
    attention=F.softmax(attention_logits,dim=1)
    values=torch.matmul(attention,value)
    return attention,values

In [11]:
seq_len,feat=3,4
query=torch.randn(seq_len,feat)
key=torch.randn(seq_len,feat)
value=torch.randn(seq_len,feat)
scaled_dot_product(query,key,value)

(tensor([[0.0650, 0.8874, 0.0476],
         [0.8402, 0.0479, 0.1119],
         [0.6512, 0.3400, 0.0088]]),
 tensor([[-0.2078, -1.4200, -0.2237,  0.6377],
         [-0.8180, -1.4825, -0.1989, -1.1468],
         [-0.7608, -1.6635, -0.2225, -0.5771]]))

In [12]:
def attention_head(num_heads,embedding_size):
    assert embedding_size%num_heads==0
    n

In [13]:
p=torch.randn(size=(3,4))
p.mean((-2,-1))

tensor(0.9311)

In [14]:
import torch.nn as nn
import torch.nn.functional as F
class LayerNorm(nn.Module):
    def __init__(self,ndim,bias):
        super().__init__()
        self.ndim=ndim
        self.weight=nn.Parameter(torch.ones(ndim))
        self.bias=nn.Parameter(torch.zeros(ndim)) if bias else None
    def forward(self,x,norm_shape,eps=1e-05,):
        return F.layer_norm(x,norm_shape,self.weight,self.bias,eps)

norm_shape=(3,4)
temp=torch.randn(norm_shape)
layer_norm=LayerNorm(ndim=(3,4),bias=True)
print(f"original form:{temp.detach()}")
print(layer_norm(temp,norm_shape).detach())

original form:tensor([[-1.2221,  0.0481, -1.3141, -0.7992],
        [ 0.7929, -0.1115, -1.5939,  0.5758],
        [ 1.5076, -0.0941, -0.4303, -1.7666]])
tensor([[-0.8792,  0.4272, -0.9738, -0.4442],
        [ 1.1932,  0.2631, -1.2616,  0.9700],
        [ 1.9283,  0.2810, -0.0648, -1.4393]])


In [15]:
x=torch.randn(size=(3,2))
y=x.view(2,3)
y.shape

torch.Size([2, 3])

In [16]:
a=torch.randn(size=(3,4))
print(a)

tensor([[-0.9195, -0.8720,  0.0729, -2.2809],
        [-0.1928,  1.1296, -0.9557, -0.3651],
        [-0.5879, -0.5506,  0.7819,  0.4923]])


In [17]:
torch.tril(a,diagonal=1)

tensor([[-0.9195, -0.8720,  0.0000,  0.0000],
        [-0.1928,  1.1296, -0.9557,  0.0000],
        [-0.5879, -0.5506,  0.7819,  0.4923]])

In [49]:
from base import AttentionHeads,LayerNorm,default_config,Block

In [58]:
#experimenting time
config=default_config()
class_exp=AttentionHeads(default_config)
temp=torch.randn(size=(32,140,768))
result=class_exp(temp)
print(f"result after the attention layer is {result.size()}")

result after the attention layer is torch.Size([32, 140, 768])


In [64]:
torch.pow(torch.tensor(3),12)

tensor(531441)

In [70]:
config=default_config
blocks=Block(config)
result=blocks(torch.randn(32,150,768))
print(f"shape is {result.shape}")

shape is torch.Size([32, 150, 768])


In [71]:
torch.max(temp)

tensor(5.0781)

In [10]:
from base import GPT
from utils import CfgNonde as CN

config=CN()

config.n_layers=3
config.emb_size=300
config.block_size=120
config.vocab_size=300
config.num_heads=3
config.model_type=None

gpt=GPT(config)

config=CN()
config.n_layers=3
config.emb_size=300
config.block_size=120
config.vocab_size=300
config.num_heads=3
config.model_type=None

gpt=GPT(config)

AttributeError: 'CfgNonde' object has no attribute 'emb_drop'